jneen/parsimmon

src/parsimmon.js, test/parsimmon.test.js
This approach is lifted wholesale from Parsec.  It turns out that it's
relatively common for several parsers to fail at the same index, which
indicates more than one possible way the user could fix the parse error.
This changes the .expected keys from strings to arrays of strings which
aggregate equal-index parse errors.  They can still be passed to
formatExpected(), so this should be non-breaking for anyone who was
simply passing the expected result in - but it will break for anyone who
was accessing the string directly.
/cc @laughinghan
=> Allow failures to aggregate messages at equal indices

README.md, src/parsimmon.js, test/parsimmon.test.js
I've stolen the implementations pretty much wholesale from the haskell
implementation; so they may well not be optimal. :|
I've taken the liberty of bumping the version number and updating the changelog; feel free to tell me to roll that back if you'd prefer to release other features (assuming you're okay with adding this to the library). 
Addresses  #29
=> Adding sepBy and sepBy1

src/parsimmon.js, test/parsimmon.test.js
Fixes #59 by checking that functions exposed to the user are passed the right types of argument.  This avoids annoyances by catching errors earlier and giving a descriptive error.
Currently, some obviously wrong stuff like—
string({ hi : 'there' })
—doesn't error until `.parse` is called on it.
Also, this mysterious beast—
p.string('a').times('wat').parse("")
—actually runs and returns `{ status: true, value: [] }`, which is fascinating but terrible.
With these changes, those go away. Unit tests to back it up.
=> Assert argument types and throw descriptive errors

package.json
The [changelog mentions](https://github.com/jneen/parsimmon/blob/master/CHANGELOG.md#version-060-2015-02-24) it's unnecessary, and it's no longer used in code.
=> Remove redundant pjs dependency from package.json

README.md, src/parsimmon.js, test/parsimmon.test.js
Fix for #54, with tests.
I'm not sure about the naming: the new `_.markLineColumn` and `_.indexLineColumn` work just like `_.mark` and `_.index`, except they also include line and column information in offset data. The names are definitely descriptive, but a little clunky. Can anyone think of better ones?
=> Create methods for marking line and column offsets

API.md
Fixed API documentation example for `parser.or` method, as referenced in #116
Furthermore, changed the parser name.
=> Fix parser.or API documentation

API.md
Adds a description for the `parser.parse(stream)` core method (#106). I thought that, given its relevance, it deserves a place on top of the list.
I added a simple example, with both success/failure cases and a tip about using `parser.desc` in order to have meaningful error messages.
English is not my main language, so any feedback/change request is highly appreciated
=> Add API documentation for parser.parse(stream)

API.md, CHANGELOG.md, src/parsimmon.js, test/parsimmon.test.js
Parser `else` method, equals to `or(Parsimmon.of(…))`. #105 
```js
var parser = P.string('a').else('x');
parser.parse('a').value; // => 'a'
parser.parse('').value;   // => 'x'
```
Includes test & doc :smile: 
Talking about the name: It seems to me that `default` may be a nice one, since this method is just providing a value if parser fails, and does *not* consume characters from the stream
```js
var parser = P.letters.default('empty');
```
=> Add `fallback` Parser method

src/parsimmon.js, test/parsimmon.test.js
closes #136 
- string and regex support
- provides as P.lookahead and P.prototype.lookahead for convenience
=> Add lookahead function

README.md, examples/.eslintrc, examples/json.js, examples/lisp.js, examples/math.js, examples/python-ish.js
Also updates all existing parsers to use an ES6 string literal inside the code so an example can be embedded easily.
=> Fixes #158; Adds Python example

.gitattributes
This fixes the bajillion errors generated when running tests on Windows.
=> Force LF line endings to fix eslint errors on Windows

src/parsimmon.js
this prevents having to build parsers and do validation at parsing time.
=> remove `chain` from sepBy1 implementation

API.md, package-lock.json, src/parsimmon.js, test/.eslintrc, test/core/bitSeq.test.js, test/core/bitSeqObj.test.js, test/core/byte.test.js, test/core/parse.test.js
Opening this PR before I begin work so that discussion can reflect over the life of the PR. #224
=> Non-byte aligned primitives.

API.md, CHANGELOG.md, package-lock.json, package.json, src/parsimmon.js, test/.eslintrc, test/core/bitSeq.test.js, test/core/bitSeqObj.test.js, test/core/byte.test.js, test/core/parse.test.js, test/core/test.test.js
=> Buffer support

src/parsimmon.js, test/core/bitSeq.test.js
So I need help writing a test that actually creates the problem I have fixed.  In the binary parser I have constructed, when the parser runs, I am getting the entire input to bitSeq, when it's supposed to just operate on a slice of the input (when embedded as part of a large parsing context).  I have fixed this issue, but I cannot seem to replicate it in a small test to prove it's an issue.
Can someone help me construct a proper test that will fail without this change?
=> Fix issue where entire (very long) input is passed to bitSeq.

examples/argv.js
Hey guys, can I suggest an example of argv (CLI) parsing? 
1\) NodeJS provides `process.argv` obviously but it's quite low-level. For example, I'd like to have
```
$ node argv.js foo -f bar
```
parsed as
```
["foo", ["f", true], "bar"]
```
instead of
```
["foo", "-f", "bar"]
```
You may also want to parse `argv`-like strings in Browser (to highlight code or whatever).
2\) Moreover, this example showcases a parsing of quoted strings:
```js
string: function() {
// one of possible quotes, then sequence of anything except that quote (unless escaped), then the same quote
return P.oneOf(`"'`).chain(function(q) {
return P.alt(
P.regex(new RegExp(`[^\\\\${q}]+`)),
P.string(`\\`).then(P.any)
)
.many()
.tie()
.skip(P.string(q));
});
}
```
with escape support, which no other example currently does …
=> Add argv parsing example

src/parsimmon.js, test/core/bitSeqObj.test.js, test/core/seqObj.test.js
Otherwise, seqObj will fail for the keys in `Object.getOwnPropertyNames(Object.prototype)`, the most likely collision being "constructor".
An alternate implementation strategy is `Object.create(null)`, but it's not supported on IE <9, and is not possible to polyfill.
=> Prefix keys in seqObj's seenKeys to avoid collisions

examples/json.js
Looks like something automatically inserted those two characters maybe?
=> Minor fix to documentation in examples/json.js

API.md, src/parsimmon.js, test/core/tieWith.test.js
An attempt to implement https://github.com/jneen/parsimmon/issues/248
The problem I have is a coverage drop from 100% to 99.8%. 
```
278 passing (184ms)
=============================== Coverage summary ===============================
Statements   : 99.81% ( 523/524 )
Branches     : 99.4% ( 165/166 )
Functions    : 100% ( 138/138 )
Lines        : 99.81% ( 523/524 )
================================================================================
```
I guess that's because of the following `!!!` (condition branch).
```js
_.tieWith = function(separator) {
assertString(separator);
return this.map(function(args) {
assertArray(args);
if (args.length) { // !!!
assertString(args[0]);
var s = args[0];
for (var i = 1; i < args.length; i++) {
assertString(args[i]);
s += separator + args[i];
}
return …
```
=> Fixes #248 Adds tieWith

API.md, package-lock.json, src/parsimmon.js, test/core/desc.test.js, test/core/makeFailure.test.js
There are certain parsers that will accept multiple strings/characters, but only return one expected value - most parsers created through the use of `Parsimmon.test()` fall into this category.  For example, `oneOf('+-%')` returns `'expected a character/byte matching function [...]'`, whereas in most cases it should probably return `expected one of '+', '-', '%'`.  Especially when you have parsers that include branches, and description arrays are merged, it can become helpful to be able to specify arrays in `.desc()` and `makeFailure()`
I've made small changes to the `.desc()` and `makeFailure()` functions, and added tests to cover both of these changes.  (None of the existing tests needed changing, although I did move the existing `makeFailure` test into a suite given that there are now …
=> Allow multiple expected values to be passed into desc and makeFailure calls

API.md
I've been constantly stumbling upon this when reading the docs. There are no links to mentioned parsers or combinators in the descriptions.
Please check out the result:
The links from the screenshot are pointing to the corresponding sections.
The rule for link replacement is:
If there's one parser or combinator in the code line, then it's replaced by the link.
Please let me know what do you think, I will continue on this if this is a good idea.
=> Improving docs

GUIDE.md
Fixes #249, adding a guide for using Parsimmon
=> Issue #249 add GUIDE.md

.travis.yml
Fixes #223.
Per instructions: https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#caching-with-npm
The `cache`, `install`, and `script` sections are automatically determined by Travis. The only thing I didn't do is manually selecting a version of `npm` to install, but I figured that it wasn't super necessary.
=> travis: Cache npm

src/parsimmon.js
I had an example of parsing a 231K file. This was taking around 56 seconds. I did profiling and found that it was calling `makeLineColumnIndex` a lot, it accounted for ~40 seconds of the time spent. While running through debugging, I found that this function was being called multiple times with the same arguments, in sequence.
I added a simple memoize with a cache of 1 (the last argument set) and the parse time went down to 13 seconds.
So I am not familiar with the internals of `parsimmon` so I can't say why the same function is being with the same arguments (maybe it is my parser implementation). The use case I have is parsing through this file, and I want to keep a lot of marks/index values because later I want to use this as an AST to edit the file quickly and precisely.
=> Add a memoize to makeLineColumnIndex for large input scenarios

API.md, src/parsimmon.js, test/core/regexp.test.js
This PR brings `s` (dotAll) flag support for regular expressions from ES2018.
More details and brief discussion is here: https://github.com/jneen/parsimmon/issues/300
=> Dotall regex support

API.md, CHANGELOG.md, src/parsimmon.js, test/.eslintrc, test/core/flags.test.js
Fixes https://github.com/jneen/parsimmon/issues/303
We saw these reports in our bug tracker:
```
Error unsupported regexp flag "n": /[0-9]/undefined 
node_modules/parsimmon/build/parsimmon.umd.min.js:1:6716 Anonymous function
node_modules/parsimmon/build/parsimmon.umd.min.js:1:6560 K
node_modules/parsimmon/build/parsimmon.umd.min.js:1:11055 Anonymous function
node_modules/parsimmon/build/parsimmon.umd.min.js:1:348 r
node_modules/parsimmon/build/parsimmon.umd.min.js:1:407 Anonymous function
node_modules/parsimmon/build/parsimmon.umd.min.js:1:199 Anonymous function
node_modules/parsimmon/build/parsimmon.umd.min.js:1 Anonymous function
webpack/bootstrap:25:3 __webpack_require__
https://mywebsite.com/static/js/main.abc.js:1:123 Anonymous function
webpack/bootstrap:25:3 __webpack_require__
``` …
=> workaround for broken Edge versions 15-18

examples/xml-ish.js
Add an example parser of a subset of XML, as @wavebeem [suggested](https://github.com/jneen/parsimmon/issues/307#issuecomment-694967351).  I tried to follow the style of other examples.
It seems the changelog hasn't mentioned addition of previous usage examples either, so I didn't touch it.
=> Add XML-ish example

README.md
Chevrotain has moved to its own org and with its own DNS name: (chevrotain.io).
The old links may stop working in 1-2 months...
=> docs: update link to performance benchmark

CHANGELOG.md, src/parsimmon.js, test/core/index.test.js
I was running into performance issues when parsing very large files because of the O(n^2) nature of the `makeLineColumnIndex` method. https://github.com/jneen/parsimmon/pull/297 added some memoization but it didn't go far enough.
Instead of just returning the cached result if it exists we now walk backwards from the index until we find a previously cached index and compute the new line and column using that info. Hopefully the comments make it clear what's happening.
This version runs in O(n) and is a drastic improvement in efficiency. Parsing time for a 25k line file drops from ~90s to under 1s.
=> fix: Improve the line/column number caching logic

CHANGELOG.md, src/parsimmon.js, test/core/mark.test.js
Ran into a very subtle bug in my [previous PR](https://github.com/jneen/parsimmon/pull/321). Basically, when parsing a new line and then an optional newline there is a double count of the line number because of the order of the branches in the walking algorithm I wrote. Flipping the order fixes it.
I added a regression test, without this change you will see `line: 3` in `end`.
=> fix: Fix line number double counting bug when parsing optional newlines

API.md
Hey, thanks for an awesome lib!
I found a small mistake in docs: `pNum.parse('3.1')` returns a failure, so I think we might want to remove it.
Executable example: https://stackblitz.com/edit/node-dthvmq
=> Remove incorrect example from API.md
